apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  # Allow this role to manage deployments, services, HPA
  # and other resources you need for deployment
  name: github-actions-role
rules:
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "list", "create", "update", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets"]
    verbs: ["get", "list", "create", "update", "delete"]
  - apiGroups: ["autoscaling"]
    resources: ["horizontalpodautoscalers"]
    verbs: ["get", "list", "create", "update", "delete"]
