apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: qace-sinatraapp-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: qace-sinatraapp
  minReplicas: 3  # minimum number of replicas
  maxReplicas: 10 # maximum number of replicas
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50  # target CPU utilization percentage

