apiVersion: v1
kind: Service
metadata:
  name: qace-sinatraapp-service
spec:
  selector:
    app: qace-sinatraapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer  # Use 'ClusterIP' or 'NodePort' if LoadBalancer is not available
