apiVersion: apps/v1
kind: Deployment
metadata:
  name: qace-sinatraapp
spec:
  replicas: 3  # Set the number of replicas to 3
  selector:
    matchLabels:
      app: qace-sinatraapp
  template:
    metadata:
      labels:
        app: qace-sinatraapp
    spec:
      containers:
        - name: qace-sinatraapp
          image: ghcr.io/triplemcoder14/qacetech-sinatraapp:latest
          ports:
            - containerPort: 8080