#!/bin/bash

set -e

# get tghe service acc token
SECRET_NAME=$(kubectl get sa github-actions-sa -o jsonpath='{.secrets[0].name}')

# xtract the service account token
kubectl get secret "$SECRET_NAME" -o jsonpath='{.data.token}' | base64 --decode > github-actions-sa-token.txt

# Extract the cluster CA certificate
kubectl get secret "$SECRET_NAME" -o jsonpath='{.data["ca.crt"]}' | base64 --decode > github-actions-ca.crt

# get k8s api-server URL
API_SERVER=$(kubectl config view --minify -o jsonpath='{.clusters[0].cluster.server}')

# generate the kubeconfig
cat <<EOF > github-actions-kubeconfig
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: $(base64 -w0 < github-actions-ca.crt)
    server: $API_SERVER
  name: minikube
contexts:
- context:
    cluster: minikube
    user: github-actions-sa
  name: github-actions-context
current-context: github-actions-context
kind: Config
users:
- name: github-actions-sa
  user:
    token: $(cat github-actions-sa-token.txt)
EOF

echo "github-actions-kubeconfig generated successfully!"
