# get the service account token
SECRET_NAME=$(kubectl get sa github-actions-sa -o jsonpath='{.secrets[0].name}')
kubectl get secret $SECRET_NAME -o jsonpath='{.data.token}' | base64 --decode > github-actions-sa-token.txt

# get the k8s cluster ca certificate
kubectl get secret $SECRET_NAME -o jsonpath='{.data["ca.crt"]}' | base64 --decode > github-actions-ca.crt

# get the cluster API url
API_SERVER=$(kubectl config view --minify -o jsonpath='{.clusters[0].cluster.server}')

# generate the kubeconfig file for gitHub actions
KUBECONFIG=$(cat <<EOF
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: $(cat github-actions-ca.crt | base64 -w0)
    server: $API_SERVER
  name: minikube
contexts:
- context:
    cluster: my-cluster
    user: github-actions-sa
  name: github-actions-context
current-context: github-actions-context
kind: Config
users:
- name: github-actions-sa
  user:
    token: $(cat github-actions-sa-token.txt)
EOF
)

echo "$KUBECONFIG" > github-actions-kubeconfig
